import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Article.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

import Container from '../../components/container'
import Header from '../../components/header'
import Footer from '../../components/footer'
import Content from '../../components/content'

export default function Home() {
  const router = useRouter()

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header>
          <div className={styles.titleContainer}>
            <img className={styles.backLogo} src='/icons8-back-50.png' onClick={() => router.back()}/>
            <h1 className={styles.title}> Welcome to NEW JIC</h1>
          </div>
          <img className={styles.chatLogo} src='/icons8-share-30.png'/>
        </Header>

        <Content className={styles.content}>
          <img className={styles.articleImage} src={'/image-not-available.jpeg'} />
          <p className={styles.articleDate}>Di update tanggal 1 Oktober 2021</p>
          <div className={styles.articleContainer}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum velit quis dui sagittis, ut auctor est viverra. Nulla sagittis vitae eros scelerisque congue. Morbi blandit neque massa. Nam vulputate leo non nisi vehicula imperdiet. Duis dapibus porttitor turpis, ornare bibendum elit dapibus eget. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce posuere feugiat malesuada. Maecenas accumsan quis quam sed tristique. Fusce nec nibh quis dolor lacinia bibendum. Sed at viverra ligula, sit amet rhoncus turpis. Sed consequat ultrices eros quis luctus.</p>
            <p>Nulla cursus nulla nec ligula laoreet scelerisque. Vivamus eget finibus dolor. Sed placerat risus ac dui egestas lobortis. Aenean fermentum, orci efficitur efficitur sodales, ante turpis ultricies massa, vel tincidunt metus leo ac mi. Vestibulum dignissim odio eu nibh semper blandit. Nulla sodales est non sem aliquet, et maximus dolor convallis. Sed scelerisque lorem venenatis faucibus vulputate.</p>
            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Donec molestie augue in orci blandit, ut commodo ipsum vulputate. Nunc porttitor ipsum elit, ut gravida magna sagittis at. Proin maximus tristique justo, vel rhoncus odio feugiat in. Fusce sollicitudin laoreet turpis in commodo. Praesent aliquam elit ac nibh tempor, eget hendrerit lorem consectetur.</p>
            <p>Fusce a libero mi. Suspendisse auctor justo in quam commodo maximus. Nulla id sem arcu. In dictum gravida justo, vulputate molestie sapien. Vestibulum a sem finibus mi fermentum lobortis. Aliquam ultrices ex in risus ultrices, eu tristique quam porta. Fusce non lectus scelerisque, venenatis nunc eu, congue arcu. Praesent sit amet turpis quis diam pellentesque pretium. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
            <p>Suspendisse auctor erat purus, a vestibulum nulla accumsan ac. In gravida est vel erat blandit porttitor. Duis nec leo tellus. Aenean in massa at purus congue auctor ut ut felis. Quisque vitae ex felis. Donec tincidunt bibendum dui, malesuada varius nibh ullamcorper a. Duis posuere dolor nec metus vulputate, eu vulputate nisl rhoncus. Phasellus lobortis risus vitae consequat pretium. In sit amet finibus ex. Nullam a tempor nunc. In massa tellus, dictum quis mauris vitae, consequat tincidunt dolor. Maecenas dapibus finibus felis eget varius. Donec malesuada placerat tempus. Vestibulum diam magna, condimentum eu tincidunt et, venenatis a nibh. Donec sollicitudin, libero non dictum semper, nulla tellus efficitur velit, nec aliquet neque nunc sed orci.</p>
          </div>
        </Content>

      </main>
    </Container>
  )
}
